### PR TITLE
Update .eslintrc.json

### PR DESCRIPTION
**Pull request by JacobMGEvans**

### CODE REVIEW

**Comment by JacobMGEvans** [comment]
@nobrayner @codyarose 
The .prettierrc does the same thing as adding them in the "options" part of the Prettier rule in ESLint

**Comment by codyarose** [comment]
> @nobrayner @codyarose 
> > moved the Prettier rules from `eslintrc` to `prettierrc`.
> 
> Why?
> 
> The .prettierrc does the same thing as adding them in the "options" part of the Prettier rule in ESLint. 
> Defeats the purpose of integrating ESLint & Prettier so it is one Formatting/Linting system and one config. 

Because there seems to be some issues with integrating ESLint and Prettier with Svelte. You can have the Prettier rules in the eslintrc as well, but without a prettierrc the formatting doesn't work properly, at least not in my testing of it.

**Comment by JacobMGEvans** [comment]
I am already regretting Svelte lmao 

Alright well let's see how the tooling evolves then

**Comment by codyarose** [comment]
It may actually be good to have both even though it is redundant: when formatting `.d.ts` files eslint and Prettier fight each other unless the Prettier rules are also in the eslintrc. I think it may be because of `prettier/recommended`

**Pull request closed without merging**
