### PR TITLE
chore: add emotion/react and emotion/styled

### LINKED ISSUE #24: 💅🏻 How to handle styling.
What are approach are we using for styling? Tailwind, Twind, Styled components, emotion... there's soo many options.

### PR DESCRIPTION
**Pull request by YPAzevedo**
Fixes #24

Adding @emotion/react and @emotion/styled to package.json

### CODE REVIEW

**Comment by YPAzevedo** [comment]
Should i remove `package-lock.json` ?

**Review by nobrayner — CHANGES_REQUESTED** [review]
You've used npm here, when the project is currently using yarn :see_no_evil:

**Comment by YPAzevedo** [comment]
> You've used npm here, when the project is currently using yarn 🙈

😅🙈 ops

**Review by nobrayner — APPROVED** [review]
LGTM

**Comment by nobrayner** [comment]
Oh, missed the merge conflict :man_facepalming:

**Review by codyarose — APPROVED** [review]
LGTM

**Pull request merged**
